table 202412Doc_4010_Consorcios_Administradoras
	lineageTag: b5ce0972-0803-4110-962f-e2bac186ddcf

	column #Data_base
		dataType: string
		lineageTag: d704ec26-66da-4fd7-9c8d-61d2a66fe57c
		summarizeBy: none
		sourceColumn: #Data_base

		annotation SummarizationSetBy = Automatic

	column Documento
		dataType: string
		lineageTag: ab96b7c9-5be1-4eb8-9edc-523e5a2a425d
		summarizeBy: none
		sourceColumn: Documento

		annotation SummarizationSetBy = Automatic

	column CNPJ_da_Administradora
		dataType: string
		lineageTag: 8d751ca4-1a71-4b76-b707-938cbb737788
		summarizeBy: none
		sourceColumn: CNPJ_da_Administradora

		annotation SummarizationSetBy = Automatic

	column Nome_da_Administradora
		dataType: string
		lineageTag: 5b1f514e-126e-4397-8f3a-60838fb23b62
		summarizeBy: none
		sourceColumn: Nome_da_Administradora

		annotation SummarizationSetBy = Automatic

	partition 202412Doc_4010_Consorcios_Administradoras = m
		mode: import
		source =
				let
				    Fonte = Csv.Document(File.Contents("C:\Users\leite\OneDrive - Univesp Acadêmico\PI IV\projeto-integrador-4\banco de dados\202412Consorcios_ADM\202412Doc_4010_Consorcios_Administradoras.csv"),[Delimiter=";", Columns=4, Encoding=1252, QuoteStyle=QuoteStyle.None]),
				    #"Cabeçalhos Promovidos" = Table.PromoteHeaders(Fonte, [PromoteAllScalars=true]),
				    #"Tipo Alterado" = Table.TransformColumnTypes(#"Cabeçalhos Promovidos",{{"#Data_base", type text}, {"Documento", type text}, {"CNPJ_da_Administradora", type text}, {"Nome_da_Administradora", type text}})
				in
				    #"Tipo Alterado"

	annotation PBI_NavigationStepName = Navegação

	annotation PBI_ResultType = Table

