table 202412Doc_4010_Consorcios_Saldos_Consolidados
	lineageTag: ebe62123-0b2b-418d-95af-77e6b3e80a7b

	column #Data_base
		dataType: string
		lineageTag: e6d31b40-4d49-4715-ab15-bec0aa3e3d42
		summarizeBy: none
		sourceColumn: #Data_base

		annotation SummarizationSetBy = Automatic

	column Documento
		dataType: string
		lineageTag: 4c5960b4-a212-4884-aada-27668d966d70
		summarizeBy: none
		sourceColumn: Documento

		annotation SummarizationSetBy = Automatic

	column Código_da_Conta
		dataType: string
		lineageTag: c449b187-1bf0-45b5-8a15-59da76ea4074
		summarizeBy: none
		sourceColumn: Código_da_Conta

		annotation SummarizationSetBy = Automatic

	column Nome_da_Conta
		dataType: string
		lineageTag: c34e2b8a-bdac-4e83-acec-d0f548cea820
		summarizeBy: none
		sourceColumn: Nome_da_Conta

		annotation SummarizationSetBy = Automatic

	column Saldo_Consolidado
		dataType: int64
		formatString: 0
		lineageTag: aadc928a-146c-426b-bb05-da9e09234306
		summarizeBy: sum
		sourceColumn: Saldo_Consolidado

		annotation SummarizationSetBy = Automatic

	partition 202412Doc_4010_Consorcios_Saldos_Consolidados = m
		mode: import
		source =
				let
				    Fonte = Csv.Document(File.Contents("C:\Users\leite\OneDrive - Univesp Acadêmico\PI IV\projeto-integrador-4\banco de dados\202412Consorcios_ADM\202412Doc_4010_Consorcios_Saldos_Consolidados.csv"),[Delimiter=";", Columns=5, Encoding=1252, QuoteStyle=QuoteStyle.None]),
				    #"Cabeçalhos Promovidos" = Table.PromoteHeaders(Fonte, [PromoteAllScalars=true]),
				    #"Tipo Alterado" = Table.TransformColumnTypes(#"Cabeçalhos Promovidos",{{"#Data_base", type text}, {"Documento", type text}, {"Código_da_Conta", type text}, {"Nome_da_Conta", type text}, {"Saldo_Consolidado", Int64.Type}})
				in
				    #"Tipo Alterado"

	annotation PBI_NavigationStepName = Navegação

	annotation PBI_ResultType = Table

