table 202412Doc_4110_Consorcios_Saldos_Consolidados
	lineageTag: 0d04817c-720f-4ff1-87e2-4320fc7fae36

	column #Data_base
		dataType: string
		lineageTag: 280f17ed-d834-4535-a853-0c987ff5751d
		summarizeBy: none
		sourceColumn: #Data_base

		annotation SummarizationSetBy = Automatic

	column Documento
		dataType: string
		lineageTag: 7295f7ae-65aa-4dd7-adad-4865d72126f0
		summarizeBy: none
		sourceColumn: Documento

		annotation SummarizationSetBy = Automatic

	column Código_da_Conta
		dataType: string
		lineageTag: b703c4b7-7800-4715-8fbb-56756b8f7e2f
		summarizeBy: none
		sourceColumn: Código_da_Conta

		annotation SummarizationSetBy = Automatic

	column Nome_da_Conta
		dataType: string
		lineageTag: 79fd19da-9f1f-4e9f-a534-81dee5f1eaa4
		summarizeBy: none
		sourceColumn: Nome_da_Conta

		annotation SummarizationSetBy = Automatic

	column Saldo_Consolidado
		dataType: int64
		formatString: 0
		lineageTag: b2377584-6e84-4229-973f-25973a9606b6
		summarizeBy: sum
		sourceColumn: Saldo_Consolidado

		annotation SummarizationSetBy = Automatic

	partition 202412Doc_4110_Consorcios_Saldos_Consolidados = m
		mode: import
		source =
				let
				    Fonte = Csv.Document(File.Contents("C:\Users\leite\OneDrive - Univesp Acadêmico\PI IV\projeto-integrador-4\banco de dados\202412Consorcios_ADM\202412Doc_4110_Consorcios_Saldos_Consolidados.csv"),[Delimiter=";", Columns=5, Encoding=1252, QuoteStyle=QuoteStyle.None]),
				    #"Cabeçalhos Promovidos" = Table.PromoteHeaders(Fonte, [PromoteAllScalars=true]),
				    #"Tipo Alterado" = Table.TransformColumnTypes(#"Cabeçalhos Promovidos",{{"#Data_base", type text}, {"Documento", type text}, {"Código_da_Conta", type text}, {"Nome_da_Conta", type text}, {"Saldo_Consolidado", Int64.Type}})
				in
				    #"Tipo Alterado"

	annotation PBI_NavigationStepName = Navegação

	annotation PBI_ResultType = Table

