table 202506Bens_Imoveis_Grupos
	lineageTag: 2e6f744d-20a0-4c98-becc-be4c00f4d326

	column #Nome_da_Administradora
		dataType: string
		lineageTag: 72d2a6ed-9d8e-4f7d-895b-0de15598843d
		summarizeBy: none
		sourceColumn: #Nome_da_Administradora

		annotation SummarizationSetBy = Automatic

	column CNPJ_da_Administradora
		dataType: string
		lineageTag: 67c221a3-95f3-47ac-baf5-6fb0950e36ca
		summarizeBy: none
		sourceColumn: CNPJ_da_Administradora

		annotation SummarizationSetBy = Automatic

	column Data_base
		dataType: string
		lineageTag: c3716ae5-c8ab-44ea-8838-bb2dba8d9a58
		summarizeBy: none
		sourceColumn: Data_base

		annotation SummarizationSetBy = Automatic

	column Código_do_grupo
		dataType: string
		lineageTag: 0cae1302-a78b-4654-bc65-0f9a5acfc9f9
		summarizeBy: none
		sourceColumn: Código_do_grupo

		annotation SummarizationSetBy = Automatic

	column Código_do_segmento
		dataType: string
		lineageTag: 00673d91-5153-4e26-8398-f2bdd799b826
		summarizeBy: none
		sourceColumn: Código_do_segmento

		annotation SummarizationSetBy = Automatic

	column Número_da_assembléia_geral_ordinária
		dataType: int64
		formatString: 0
		lineageTag: ae32f37a-be80-47c7-96ce-77b963d5a917
		summarizeBy: sum
		sourceColumn: Número_da_assembléia_geral_ordinária

		annotation SummarizationSetBy = Automatic

	column Valor_médio_do_bem
		dataType: double
		lineageTag: d5840dc4-a854-4b1e-b3ca-cb5fce0ae26f
		summarizeBy: sum
		sourceColumn: Valor_médio_do_bem

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column Índice_de_correção
		dataType: string
		lineageTag: 0410041c-28df-43f0-b959-71a2fbcd8c15
		summarizeBy: none
		sourceColumn: Índice_de_correção

		annotation SummarizationSetBy = Automatic

	column Taxa_de_administração
		dataType: double
		lineageTag: 752918a4-dd97-4596-b3a1-5103c9d68f12
		summarizeBy: sum
		sourceColumn: Taxa_de_administração

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column Prazo_do_grupo_em_meses
		dataType: int64
		formatString: 0
		lineageTag: 48ab2959-3e07-4486-a5f2-82199e6a2dd5
		summarizeBy: sum
		sourceColumn: Prazo_do_grupo_em_meses

		annotation SummarizationSetBy = Automatic

	column Quantidade_de_cotas_ativas_em_dia
		dataType: int64
		formatString: 0
		lineageTag: 4af85b4f-8d23-4038-9a8c-01c1dbddba34
		summarizeBy: sum
		sourceColumn: Quantidade_de_cotas_ativas_em_dia

		annotation SummarizationSetBy = Automatic

	column Quantidade_de_cotas_ativas_contempladas_inadimplentes
		dataType: int64
		formatString: 0
		lineageTag: ee5e6378-f98f-455c-ae43-ffb461aa3f1e
		summarizeBy: sum
		sourceColumn: Quantidade_de_cotas_ativas_contempladas_inadimplentes

		annotation SummarizationSetBy = Automatic

	column Quantidade_de_cotas_ativas_não_contempladas_inadimplentes
		dataType: int64
		formatString: 0
		lineageTag: 3955e28b-bc03-48eb-977e-35c374babada
		summarizeBy: sum
		sourceColumn: Quantidade_de_cotas_ativas_não_contempladas_inadimplentes

		annotation SummarizationSetBy = Automatic

	column Quantidade_de_cotas_ativas_contempladas_no_mês
		dataType: int64
		formatString: 0
		lineageTag: cdac58a6-a74f-4379-8405-dc95e6c48455
		summarizeBy: sum
		sourceColumn: Quantidade_de_cotas_ativas_contempladas_no_mês

		annotation SummarizationSetBy = Automatic

	column Quantidade_de_cotas_excluídas
		dataType: int64
		formatString: 0
		lineageTag: e0a87b7d-d5ac-440f-801d-ddd7edc55d71
		summarizeBy: sum
		sourceColumn: Quantidade_de_cotas_excluídas

		annotation SummarizationSetBy = Automatic

	column Quantidade_de_cotas_ativas_quitadas
		dataType: int64
		formatString: 0
		lineageTag: 3c1252a4-685d-4238-acc1-10bd0feca09e
		summarizeBy: sum
		sourceColumn: Quantidade_de_cotas_ativas_quitadas

		annotation SummarizationSetBy = Automatic

	column Quantidade_de_cotas_ativas_com_crédito_pendente_de_utilização
		dataType: int64
		formatString: 0
		lineageTag: a2af0f76-3963-429a-b5b7-d0e4ea3f57f2
		summarizeBy: sum
		sourceColumn: Quantidade_de_cotas_ativas_com_crédito_pendente_de_utilização

		annotation SummarizationSetBy = Automatic

	partition 202506Bens_Imoveis_Grupos = m
		mode: import
		source =
				let
				    Fonte = Csv.Document(File.Contents("C:\Users\leite\OneDrive - Univesp Acadêmico\PI IV\projeto-integrador-4\banco de dados\202506Consorcios\202506Bens_Imoveis_Grupos.csv"),[Delimiter=";", Columns=17, Encoding=1252, QuoteStyle=QuoteStyle.None]),
				    #"Cabeçalhos Promovidos" = Table.PromoteHeaders(Fonte, [PromoteAllScalars=true]),
				    #"Tipo Alterado" = Table.TransformColumnTypes(#"Cabeçalhos Promovidos",{{"#Nome_da_Administradora", type text}, {"CNPJ_da_Administradora", type text}, {"Data_base", type text}, {"Código_do_grupo", type text}, {"Código_do_segmento", type text}, {"Número_da_assembléia_geral_ordinária", Int64.Type}, {"Valor_médio_do_bem", type number}, {"Índice_de_correção", type text}, {"Taxa_de_administração", type number}, {"Prazo_do_grupo_em_meses", Int64.Type}, {"Quantidade_de_cotas_ativas_em_dia", Int64.Type}, {"Quantidade_de_cotas_ativas_contempladas_inadimplentes", Int64.Type}, {"Quantidade_de_cotas_ativas_não_contempladas_inadimplentes", Int64.Type}, {"Quantidade_de_cotas_ativas_contempladas_no_mês", Int64.Type}, {"Quantidade_de_cotas_excluídas", Int64.Type}, {"Quantidade_de_cotas_ativas_quitadas", Int64.Type}, {"Quantidade_de_cotas_ativas_com_crédito_pendente_de_utilização", Int64.Type}})
				in
				    #"Tipo Alterado"

	annotation PBI_NavigationStepName = Navegação

	annotation PBI_ResultType = Table

