table 202506Bens_Moveis_Grupos
	lineageTag: b7047456-8623-4a38-bf01-e944a529382c

	column #Nome_da_Administradora
		dataType: string
		lineageTag: 23e25f78-aa59-4f79-8bbf-63b1d5a7a774
		summarizeBy: none
		sourceColumn: #Nome_da_Administradora

		annotation SummarizationSetBy = Automatic

	column CNPJ_da_Administradora
		dataType: string
		lineageTag: fea668f2-bc64-4e77-8027-90c5a5cbb564
		summarizeBy: none
		sourceColumn: CNPJ_da_Administradora

		annotation SummarizationSetBy = Automatic

	column Data_base
		dataType: string
		lineageTag: 24b526bb-2853-4dd9-9914-6ac9c2b8e541
		summarizeBy: none
		sourceColumn: Data_base

		annotation SummarizationSetBy = Automatic

	column Código_do_grupo
		dataType: string
		lineageTag: a78f57d5-b3d1-45a1-993e-94b6fe109bf1
		summarizeBy: none
		sourceColumn: Código_do_grupo

		annotation SummarizationSetBy = Automatic

	column Código_do_segmento
		dataType: string
		lineageTag: 09e25b1d-2e8a-4b19-82f1-1b9b0b3fd07a
		summarizeBy: none
		sourceColumn: Código_do_segmento

		annotation SummarizationSetBy = Automatic

	column Número_da_assembléia_geral_ordinária
		dataType: int64
		formatString: 0
		lineageTag: 89e98750-0017-4ad7-97ad-75c328219518
		summarizeBy: sum
		sourceColumn: Número_da_assembléia_geral_ordinária

		annotation SummarizationSetBy = Automatic

	column Valor_médio_do_bem
		dataType: double
		lineageTag: e86b5531-efcc-4342-ae20-d175a2062272
		summarizeBy: sum
		sourceColumn: Valor_médio_do_bem

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column Índice_de_correção
		dataType: string
		lineageTag: 7a699455-381f-453c-9793-b279f4bbc009
		summarizeBy: none
		sourceColumn: Índice_de_correção

		annotation SummarizationSetBy = Automatic

	column Taxa_de_administração
		dataType: double
		lineageTag: 59e98248-2766-47a0-acea-f5eb8448709f
		summarizeBy: sum
		sourceColumn: Taxa_de_administração

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column Prazo_do_grupo_em_meses
		dataType: int64
		formatString: 0
		lineageTag: 53ed6caa-79b5-4c14-aa50-ffe5acb2a83a
		summarizeBy: sum
		sourceColumn: Prazo_do_grupo_em_meses

		annotation SummarizationSetBy = Automatic

	column Quantidade_de_cotas_ativas_em_dia
		dataType: int64
		formatString: 0
		lineageTag: d79651fc-5159-4c23-af87-bf32bab80af8
		summarizeBy: sum
		sourceColumn: Quantidade_de_cotas_ativas_em_dia

		annotation SummarizationSetBy = Automatic

	column Quantidade_de_cotas_ativas_contempladas_inadimplentes
		dataType: int64
		formatString: 0
		lineageTag: 76a51da7-5965-46eb-981d-2733d6fb48d7
		summarizeBy: sum
		sourceColumn: Quantidade_de_cotas_ativas_contempladas_inadimplentes

		annotation SummarizationSetBy = Automatic

	column Quantidade_de_cotas_ativas_não_contempladas_inadimplentes
		dataType: int64
		formatString: 0
		lineageTag: ed05753f-9a15-45d4-8839-ec948449dd94
		summarizeBy: sum
		sourceColumn: Quantidade_de_cotas_ativas_não_contempladas_inadimplentes

		annotation SummarizationSetBy = Automatic

	column Quantidade_de_cotas_ativas_contempladas_no_mês
		dataType: int64
		formatString: 0
		lineageTag: 211f8c25-60d3-4c56-ab1e-756910583599
		summarizeBy: sum
		sourceColumn: Quantidade_de_cotas_ativas_contempladas_no_mês

		annotation SummarizationSetBy = Automatic

	column Quantidade_de_cotas_excluídas
		dataType: int64
		formatString: 0
		lineageTag: ed87888c-41c4-434e-b149-27f184235501
		summarizeBy: sum
		sourceColumn: Quantidade_de_cotas_excluídas

		annotation SummarizationSetBy = Automatic

	column Quantidade_de_cotas_ativas_quitadas
		dataType: int64
		formatString: 0
		lineageTag: d056200b-3c1d-4cbe-9c43-ef558f6df7ba
		summarizeBy: sum
		sourceColumn: Quantidade_de_cotas_ativas_quitadas

		annotation SummarizationSetBy = Automatic

	column Quantidade_de_cotas_ativas_com_crédito_pendente_de_utilização
		dataType: int64
		formatString: 0
		lineageTag: 0e89bbfa-3658-4a04-9db9-96a4b7cd625c
		summarizeBy: sum
		sourceColumn: Quantidade_de_cotas_ativas_com_crédito_pendente_de_utilização

		annotation SummarizationSetBy = Automatic

	partition 202506Bens_Moveis_Grupos = m
		mode: import
		source =
				let
				    Fonte = Csv.Document(File.Contents("C:\Users\leite\OneDrive - Univesp Acadêmico\PI IV\projeto-integrador-4\banco de dados\202506Consorcios\202506Bens_Moveis_Grupos.csv"),[Delimiter=";", Columns=17, Encoding=1252, QuoteStyle=QuoteStyle.None]),
				    #"Cabeçalhos Promovidos" = Table.PromoteHeaders(Fonte, [PromoteAllScalars=true]),
				    #"Tipo Alterado" = Table.TransformColumnTypes(#"Cabeçalhos Promovidos",{{"#Nome_da_Administradora", type text}, {"CNPJ_da_Administradora", type text}, {"Data_base", type text}, {"Código_do_grupo", type text}, {"Código_do_segmento", type text}, {"Número_da_assembléia_geral_ordinária", Int64.Type}, {"Valor_médio_do_bem", type number}, {"Índice_de_correção", type text}, {"Taxa_de_administração", type number}, {"Prazo_do_grupo_em_meses", Int64.Type}, {"Quantidade_de_cotas_ativas_em_dia", Int64.Type}, {"Quantidade_de_cotas_ativas_contempladas_inadimplentes", Int64.Type}, {"Quantidade_de_cotas_ativas_não_contempladas_inadimplentes", Int64.Type}, {"Quantidade_de_cotas_ativas_contempladas_no_mês", Int64.Type}, {"Quantidade_de_cotas_excluídas", Int64.Type}, {"Quantidade_de_cotas_ativas_quitadas", Int64.Type}, {"Quantidade_de_cotas_ativas_com_crédito_pendente_de_utilização", Int64.Type}})
				in
				    #"Tipo Alterado"

	annotation PBI_NavigationStepName = Navegação

	annotation PBI_ResultType = Table

