table 202506Consorcios_UF
	lineageTag: 6a964da1-a27a-46f7-a185-9566281d52c0

	column #Data_base
		dataType: string
		lineageTag: 9aa414ac-383f-411c-9eed-141136c4a5f1
		summarizeBy: none
		sourceColumn: #Data_base

		annotation SummarizationSetBy = Automatic

	column CNPJ_da_Administradora
		dataType: string
		lineageTag: 78356ddc-41f0-4903-bf32-dce2af9fbe48
		summarizeBy: none
		sourceColumn: CNPJ_da_Administradora

		annotation SummarizationSetBy = Automatic

	column Nome_da_Administradora
		dataType: string
		lineageTag: 6d482c83-bab3-448e-9f6f-639b9d03e8aa
		summarizeBy: none
		sourceColumn: Nome_da_Administradora

		annotation SummarizationSetBy = Automatic

	column Código_do_segmento
		dataType: string
		lineageTag: 3cb7e5cb-fb6e-4214-8f5b-074681b9ee13
		summarizeBy: none
		sourceColumn: Código_do_segmento

		annotation SummarizationSetBy = Automatic

	column Unidade_da_Federação_do_consorciado
		dataType: string
		lineageTag: 48e4dc3e-dec7-42e3-b901-8497b36aeb1a
		summarizeBy: none
		sourceColumn: Unidade_da_Federação_do_consorciado

		annotation SummarizationSetBy = Automatic

	column Quantidade_de_consorciados_ativos_contemplados_por_lance
		dataType: int64
		formatString: 0
		lineageTag: cf992373-6045-49c2-9370-ffe19e85a4e7
		summarizeBy: sum
		sourceColumn: Quantidade_de_consorciados_ativos_contemplados_por_lance

		annotation SummarizationSetBy = Automatic

	column Quantidade_de_consorciados_ativos_contemplados_por_sorteio
		dataType: int64
		formatString: 0
		lineageTag: a7f74e7c-343f-4b54-bd30-06c2f318b47d
		summarizeBy: sum
		sourceColumn: Quantidade_de_consorciados_ativos_contemplados_por_sorteio

		annotation SummarizationSetBy = Automatic

	column Quantidade_de_consorciados_ativos_não_contemplados
		dataType: int64
		formatString: 0
		lineageTag: 18af7ea5-6346-4ae2-b37a-78e9651e8a6b
		summarizeBy: sum
		sourceColumn: Quantidade_de_consorciados_ativos_não_contemplados

		annotation SummarizationSetBy = Automatic

	column Quantidade_de_consorciados_excluídos_contemplados
		dataType: int64
		formatString: 0
		lineageTag: c92fae1f-eb30-4792-bac3-e1705b323ffd
		summarizeBy: sum
		sourceColumn: Quantidade_de_consorciados_excluídos_contemplados

		annotation SummarizationSetBy = Automatic

	column Quantidade_de_consorciados_excluídos_não_contemplados
		dataType: int64
		formatString: 0
		lineageTag: cac3fca2-789d-4312-b74b-2a7e5adb2419
		summarizeBy: sum
		sourceColumn: Quantidade_de_consorciados_excluídos_não_contemplados

		annotation SummarizationSetBy = Automatic

	column Quantidade_de_consorciados_ativos_contemplados_por_lance_no_trimestre
		dataType: int64
		formatString: 0
		lineageTag: d9378690-7fd4-4742-b80d-9f7e963d841b
		summarizeBy: sum
		sourceColumn: Quantidade_de_consorciados_ativos_contemplados_por_lance_no_trimestre

		annotation SummarizationSetBy = Automatic

	column Quantidade_de_consorciados_ativos_contemplados_por_sorteio_no_trimestre
		dataType: int64
		formatString: 0
		lineageTag: cbcfb98c-7d3b-4312-9e08-54db1b8731bb
		summarizeBy: sum
		sourceColumn: Quantidade_de_consorciados_ativos_contemplados_por_sorteio_no_trimestre

		annotation SummarizationSetBy = Automatic

	column Quantidade_de_consorciados_excluídos_contemplados_no_trimestre
		dataType: int64
		formatString: 0
		lineageTag: 0938c176-e018-4f3f-87bf-fd4b204e1b26
		summarizeBy: sum
		sourceColumn: Quantidade_de_consorciados_excluídos_contemplados_no_trimestre

		annotation SummarizationSetBy = Automatic

	column Quantidade_de_adesões_no_trimestre
		dataType: int64
		formatString: 0
		lineageTag: e3009eba-8b7b-419b-9f3a-f31238c854fb
		summarizeBy: sum
		sourceColumn: Quantidade_de_adesões_no_trimestre

		annotation SummarizationSetBy = Automatic

	partition 202506Consorcios_UF = m
		mode: import
		source =
				let
				    Fonte = Csv.Document(File.Contents("C:\Users\leite\OneDrive - Univesp Acadêmico\PI IV\projeto-integrador-4\banco de dados\202506Consorcios_UF\202506Consorcios_UF.csv"),[Delimiter=";", Columns=14, Encoding=1252, QuoteStyle=QuoteStyle.None]),
				    #"Cabeçalhos Promovidos" = Table.PromoteHeaders(Fonte, [PromoteAllScalars=true]),
				    #"Tipo Alterado" = Table.TransformColumnTypes(#"Cabeçalhos Promovidos",{{"#Data_base", type text}, {"CNPJ_da_Administradora", type text}, {"Nome_da_Administradora", type text}, {"Código_do_segmento", type text}, {"Unidade_da_Federação_do_consorciado", type text}, {"Quantidade_de_consorciados_ativos_contemplados_por_lance", Int64.Type}, {"Quantidade_de_consorciados_ativos_contemplados_por_sorteio", Int64.Type}, {"Quantidade_de_consorciados_ativos_não_contemplados", Int64.Type}, {"Quantidade_de_consorciados_excluídos_contemplados", Int64.Type}, {"Quantidade_de_consorciados_excluídos_não_contemplados", Int64.Type}, {"Quantidade_de_consorciados_ativos_contemplados_por_lance_no_trimestre", Int64.Type}, {"Quantidade_de_consorciados_ativos_contemplados_por_sorteio_no_trimestre", Int64.Type}, {"Quantidade_de_consorciados_excluídos_contemplados_no_trimestre", Int64.Type}, {"Quantidade_de_adesões_no_trimestre", Int64.Type}})
				in
				    #"Tipo Alterado"

	annotation PBI_NavigationStepName = Navegação

	annotation PBI_ResultType = Table

