table Dim_Segmentos
	lineageTag: 72a610af-1154-44ad-91a0-75bc4dea5bd3

	column Código_do_segmento
		dataType: string
		lineageTag: c0dc1a8c-fbce-46dd-ac0a-ecb1d12fef3a
		summarizeBy: none
		sourceColumn: Código_do_segmento

		annotation SummarizationSetBy = Automatic

	column Segmento
		dataType: string
		lineageTag: 8a37fc3e-a983-494b-8a2c-ac88a3b17d3e
		summarizeBy: none
		sourceColumn: Segmento

		annotation SummarizationSetBy = Automatic

	partition Dim_Segmentos = m
		mode: import
		source =
				let
				    Fonte = Excel.Workbook(File.Contents("C:\Users\leite\OneDrive - Univesp Acadêmico\PI IV\projeto-integrador-4\banco de dados\Dimensao.xlsx"), null, true),
				    Dim_Segmentos_Sheet = Fonte{[Item="Dim_Segmentos",Kind="Sheet"]}[Data],
				    #"Cabeçalhos Promovidos" = Table.PromoteHeaders(Dim_Segmentos_Sheet, [PromoteAllScalars=true]),
				    #"Tipo Alterado" = Table.TransformColumnTypes(#"Cabeçalhos Promovidos",{{"Código_do_segmento", type text}, {"Segmento", type text}})
				in
				    #"Tipo Alterado"

	annotation PBI_NavigationStepName = Navegação

	annotation PBI_ResultType = Table

